apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
spec:
  host: app-petclinic-uat.apps.cluster-ottawa-7b89.ottawa-7b89.example.opentlc.com
status:
  ingress:
  - conditions:
    host: app-petclinic-uat.apps.cluster-ottawa-7b89.ottawa-7b89.example.opentlc.com
