apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: selenium
  name: selenium-hub
  namespace: cicd
spec:
  host: selenium-hub-cicd.apps.cluster-ott-407e.ott-407e.example.opentlc.com
  port:
    targetPort: 4444-tcp
  subdomain: ""
  to:
    kind: Service
    name: selenium-hub
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    host: selenium-hub-cicd.apps.cluster-ott-407e.ott-407e.example.opentlc.com
    routerCanonicalHostname: apps.cluster-ott-407e.ott-407e.example.opentlc.com
    routerName: default
    wildcardPolicy: None
