apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../bases
namespace: cicd
resources:
- namespace.yaml
patchesJson6902:
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: selenium-hub
  path: route-patch.json
